"""Weekly performance report per PRD section 17."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from sqlmodel import Session, select

from freelance_os.db import get_engine
from freelance_os.models import Lead, LeadStatus, Outcome, OutcomeResult, ProposalDraft


def generate_weekly_report(cfg: dict, export_path: Optional[str] = None) -> str:
    """Generate a weekly report from DB data and return as string."""
    engine = get_engine(cfg["paths"]["database_path"])

    with Session(engine) as session:
        all_leads = session.exec(select(Lead)).all()
        all_outcomes = session.exec(select(Outcome)).all()
        all_drafts = session.exec(select(ProposalDraft)).all()

    # Counts
    total_leads = len(all_leads)
    new_leads = sum(1 for l in all_leads if l.status == LeadStatus.NEW)
    scored_leads = sum(1 for l in all_leads if l.status in (
        LeadStatus.SCORED, LeadStatus.DRAFTED, LeadStatus.APPROVED_TO_APPLY,
        LeadStatus.APPLIED_MANUALLY, LeadStatus.INTERVIEW, LeadStatus.WON,
        LeadStatus.LOST,
    ))
    rejected_leads = sum(1 for l in all_leads if l.status == LeadStatus.REJECTED)
    drafted = sum(1 for l in all_leads if l.status in (
        LeadStatus.DRAFTED, LeadStatus.APPROVED_TO_APPLY, LeadStatus.APPLIED_MANUALLY,
        LeadStatus.INTERVIEW, LeadStatus.WON,
    ))
    applied = sum(1 for l in all_leads if l.status in (
        LeadStatus.APPLIED_MANUALLY, LeadStatus.INTERVIEW, LeadStatus.WON,
    ))
    interviews = sum(1 for l in all_leads if l.status in (
        LeadStatus.INTERVIEW, LeadStatus.WON,
    ))
    won = sum(1 for l in all_leads if l.status == LeadStatus.WON)
    lost = sum(1 for l in all_leads if l.status == LeadStatus.LOST)

    # Revenue
    won_outcomes = [o for o in all_outcomes if o.result == OutcomeResult.WON]
    estimated_revenue = sum(o.final_budget or 0 for o in won_outcomes)
    actual_revenue = estimated_revenue  # MVP: same as estimated

    # Win rate
    total_applied = applied + lost
    win_rate = (won / total_applied * 100) if total_applied > 0 else 0.0

    # Avg score
    scored_with_score = [l for l in all_leads if l.lead_score is not None]
    avg_score = (
        sum(l.lead_score for l in scored_with_score) / len(scored_with_score)
        if scored_with_score else 0.0
    )

    # Common rejection reasons from outcomes
    loss_reasons = [o.reason for o in all_outcomes if o.result == OutcomeResult.LOST and o.reason]

    # Source breakdown
    sources: dict = {}
    for lead in all_leads:
        sources[lead.source] = sources.get(lead.source, 0) + 1

    report_date = datetime.utcnow().strftime("%Y-%m-%d")

    lines = [
        f"# Weekly Freelance Report — {report_date}",
        "",
        "## Pipeline Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Leads imported | {total_leads} |",
        f"| New (unscored) | {new_leads} |",
        f"| Scored | {scored_leads} |",
        f"| Rejected | {rejected_leads} |",
        f"| Proposals drafted | {drafted} |",
        f"| Manually submitted | {applied} |",
        f"| Interviews | {interviews} |",
        f"| Won contracts | {won} |",
        f"| Lost opportunities | {lost} |",
        "",
        "## Revenue",
        "",
        f"| Metric | Amount |",
        f"|--------|--------|",
        f"| Estimated revenue | ${estimated_revenue:,.0f} |",
        f"| Actual revenue | ${actual_revenue:,.0f} |",
        f"| Win rate | {win_rate:.1f}% |",
        "",
        "## Lead Quality",
        "",
        f"- Average lead score: {avg_score:.1f}",
        f"- Total drafts created: {len(all_drafts)}",
        "",
        "## Lead Sources",
        "",
    ]

    for source, count in sorted(sources.items(), key=lambda x: -x[1]):
        lines.append(f"- {source}: {count}")

    lines += [
        "",
        "## Common Rejection Reasons",
        "",
    ]

    if loss_reasons:
        for r in loss_reasons[:10]:
            lines.append(f"- {r}")
    else:
        lines.append("- No loss reasons recorded yet.")

    lines += [
        "",
        "---",
        "_Report generated by freelance-os. All data is local-only._",
    ]

    report = "\n".join(lines)

    if export_path:
        Path(export_path).write_text(report, encoding="utf-8")

    return report


