from enum import Enum


class LeadStatus(str, Enum):
    NEW = "NEW"
    SCORED = "SCORED"
    DRAFTED = "DRAFTED"
    APPROVED_TO_APPLY = "APPROVED_TO_APPLY"
    APPLIED_MANUALLY = "APPLIED_MANUALLY"
    INTERVIEW = "INTERVIEW"
    WON = "WON"
    LOST = "LOST"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class Decision(str, Enum):
    DRAFT_NOW = "DRAFT_NOW"
    WATCH = "WATCH"
    MAYBE = "MAYBE"
    REJECT = "REJECT"


class ClientProjectStatus(str, Enum):
    INTAKE = "INTAKE"
    ACTIVE = "ACTIVE"
    WAITING_ON_CLIENT = "WAITING_ON_CLIENT"
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    REVISION = "REVISION"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"


class OutcomeResult(str, Enum):
    WON = "WON"
    LOST = "LOST"
    CANCELLED = "CANCELLED"
    WITHDRAWN = "WITHDRAWN"
    NO_RESPONSE = "NO_RESPONSE"


# Reason codes for lead scoring (PRD section 10.4)
REASON_CODES = [
    "TECH_STACK_MATCH",
    "HIGH_BUDGET_FIT",
    "CLEAR_SCOPE",
    "STRONG_PORTFOLIO_MATCH",
    "LOW_BUDGET",
    "SCOPE_CREEP_RISK",
    "UNREALISTIC_DEADLINE",
    "UNSUPPORTED_STACK",
    "PAYMENT_RISK",
    "UNPAID_TEST_REQUEST",
    "PLATFORM_BYPASS_RISK",
    "VAGUE_FIXED_PRICE",
    "SUSPICIOUS_CLIENT",
    "NEGATIVE_REVIEW_PATTERN",
    "EASY_LANGUAGE_RED_FLAG",
    "UNCLEAR_DELIVERABLES",
    "FREE_CONSULT_REQUEST",
]
