"""Tmux session script generator — generates shell scripts, never auto-launches."""

from __future__ import annotations

from pathlib import Path


def generate_tmux_script(project_name: str, scripts_dir: Path = Path("scripts")) -> Path:
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script_path = scripts_dir / "start_client_session.sh"

    content = f"""#!/usr/bin/env bash
# GENERATED by freelance-os — review before running
# Usage: bash {script_path} [project_name]
set -e

PROJECT="${{1:-{project_name}}}"
SESSION="client-$PROJECT"

echo "Starting tmux session: $SESSION"

tmux new-session -d -s "$SESSION" -n "orchestrator"
tmux new-window -t "$SESSION" -n "coder"
tmux new-window -t "$SESSION" -n "qa"
tmux new-window -t "$SESSION" -n "docs-delivery"
tmux new-window -t "$SESSION" -n "git-logs"

tmux select-window -t "$SESSION:orchestrator"
tmux attach-session -t "$SESSION"
"""
    script_path.write_text(content)
    script_path.chmod(0o755)
    return script_path
